<?php

return [
    'DB_HOST' => '127.0.0.1',
    'DB_PORT' => 3306,
    'DB_NAME' => 'ultimate_back_office',
    'DB_USER' => 'your_database_user',
    'DB_PASSWORD' => 'your_database_password',
    'DB_SSL_MODE' => '',
    'DB_SSL_CA' => '',
    'APP_ENV' => 'staging',
    'APP_DEBUG' => true,
    'APP_BASE_URL' => 'https://staging-app.ultimatebackoffice.com',
    'ACCOUNTS_BASE_URL' => 'https://staging-accounts.ultimatebackoffice.com',
    'SESSION_COOKIE_NAME' => '',
    'SESSION_COOKIE_DOMAIN' => '',
    'STRIPE_SECRET_KEY' => '',
    'STRIPE_PUBLISHABLE_KEY' => '',
    'STRIPE_WEBHOOK_SECRET' => '',
    'STRIPE_247SP_PRICE_ID' => '',
    'STRIPE_247SP_SETUP_FEE_PRICE_ID' => '',
    'STRIPE_SUCCESS_URL' => 'https://staging-accounts.ultimatebackoffice.com/billing.php?checkout=success&business_id={BUSINESS_ID}&checkout_session_id={CHECKOUT_SESSION_ID}',
    'STRIPE_CANCEL_URL' => 'https://staging-accounts.ultimatebackoffice.com/billing.php?checkout=cancelled&business_id={BUSINESS_ID}',
    'NAMECHEAP_API_USER' => '',
    'NAMECHEAP_API_KEY' => '',
    'NAMECHEAP_USERNAME' => '',
    'NAMECHEAP_CLIENT_IP' => '',
    'NAMECHEAP_SANDBOX' => true,
    'DOMAIN_DEFAULT_REGISTRAR' => 'namecheap',
    'DOMAIN_TARGET_IPV4' => '',
    'DOMAIN_TARGET_IPV6' => '',
    'DOMAIN_WWW_CNAME' => '',
    'DOMAIN_TXT_VERIFICATION_NAME' => '',
    'DOMAIN_TXT_VERIFICATION_VALUE' => '',
    'DOMAIN_MAIL_MX_HOST' => '',
];
